### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by TimPhoeniX** [SLGamesCregg/GodotXbox#1]
I need to add some more stuff, but I can't get self-compiled dll to work on Xbox.
It does work on PC, and dll provided does work on both, but I get `Error 126: The specified module could not be found.` on Xbox with my own dll.

**Comment by TimPhoeniX** [comment]
I had to fix directory dependencies to have dll link to proper, uwp store-compliant libs.

**Comment by CreggHancock** [comment]
Yes, sorry for taking so long to get back. Getting those dependencies all set up to build correctly is quite a pain. I planned on writing a doc explaining how to compile the GDNative plugin yourself but haven't gotten around to it.
